name: Deploy to SiteValley

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Upload files to SiteValley via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: shared02-atl.srv-infra.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /home/vinzidea/public_html/wp-content/themes/vinz-ideas-theme/
        state-name: .ftp-deploy-sync-state.json
        dangerous-clean-slate: false
